### ISSUE TITLE
where is the output of  the  butterworth_bandpass_filter    at line 106  in getAllData.py? 

### ISSUE THREAD

**Issue by chumingqian** [Wang-Fulin-SDUWH/HeartSound#1]
Hi, @Wang-Fulin-SDUWH :
         Could you explain  where is the output of  the  butterworth_bandpass_filter    at line 106  in getAllData.py,    is  there  another  palce  has  called    the  output of  the  butterworth_bandpass_filter.
     thanks  in advance.

**Comment by ZhangzhengTomiHoYo** [comment]
> 嗨，@Wang-福林-SDUWH：您能解释一下 getAllData.py 中 106 行的butterworth_bandpass_filter输出在哪里吗，是否有另一个 palce 称为butterworth_bandpass_filter的输出。提前谢谢。

I have the same confusion. That means there is no filter before the data is put into the model.

**Comment by Wang-Fulin-SDUWH** [comment]
That should actually be fixed. “signal=butter(…)” is correct. Thanks for pointing out the bug.
